"""
ActionSequenceScheduler — unified timeline scheduler for multi-channel execution.
v4.5.0 §7.2

Orchestrates ActionSequence scripts distributed across avatar_channel,
mouse_channel, voice_channel (and bubble for text bubbles). Execution is
driven by TTS streaming progress (elapsed_ms) as the single clock source.

Key behaviours:
  - TTS-progress-driven dispatch (start_ms <= elapsed_ms + 50ms tolerance)
  - skip_decision=True actions have lower priority than user-triggered actions
  - Mouse deadline enforcement (force-jump if near deadline)
  - User mid-speech interrupt stops all channels immediately
  - CharDurationPredictor fallback when CosyVoice word-alignment unavailable
"""
from __future__ import annotations

import asyncio
import logging
import uuid
from collections.abc import AsyncIterator, Awaitable, Callable
from dataclasses import dataclass, field
from typing import Any

from src.config.runtime import RuntimeConfig  # v4.5.0 §0.5
from src.execution.tts_service.char_duration_predictor import (
    CharDurationPredictor,
)
from src.execution.state_bus import StateBus  # v4.5.0 §7.6

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Channel name constants — 项目宪法 §2.3
# ---------------------------------------------------------------------------

CHANNEL_AVATAR = "avatar"
CHANNEL_MOUSE = "mouse"
CHANNEL_VOICE = "voice"
CHANNEL_BUBBLE = "bubble"

VALID_CHANNELS: frozenset[str] = frozenset(
    {CHANNEL_AVATAR, CHANNEL_MOUSE, CHANNEL_VOICE, CHANNEL_BUBBLE}
)

# Default dispatch tolerance in ms — v4.5.0 §7.2.2
DEFAULT_DISPATCH_TOLERANCE_MS = 50

# Default mouse deadline threshold — if remaining time < this, force-jump
DEFAULT_MOUSE_DEADLINE_THRESHOLD_MS = 100


# ---------------------------------------------------------------------------
# Data structures — v4.5.0 §7.2.1
# ---------------------------------------------------------------------------

@dataclass
class Action:
    """A single action in an ActionSequence.

    v4.5.0 §7.2.1: Each action targets one channel and carries timing info.
    """

    channel: str
    """Target channel: avatar, mouse, voice, or bubble."""

    type: str
    """Action type: expression, motion, move_to, click, text, etc."""

    start_ms: int
    """Start time relative to sequence start in milliseconds."""

    value: str | None = None
    """Action value (e.g., expression name, text content)."""

    target: dict[str, Any] | None = None  # pyright: ignore[reportExplicitAny]
    """Target coordinates for mouse actions: {"x": int, "y": int}."""

    duration_ms: int | None = None
    """Duration in milliseconds (for expressions, motions)."""

    deadline_ms: int | None = None
    """Deadline by which the action must complete (for mouse actions)."""

    def __post_init__(self) -> None:
        """Validate channel name — 项目宪法 §2.1 zero-tolerance naming."""
        if self.channel not in VALID_CHANNELS:
            logger.warning(
                "Unknown channel %r in action — valid channels: %s. trace_id=TBD",
                self.channel,
                sorted(VALID_CHANNELS),
            )


@dataclass
class ActionSequence:
    """A timeline of multi-channel actions to execute.

    v4.5.0 §7.2.1: Generated by the scheduler, distributed to channels.
    """

    sequence_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    """Unique identifier for this sequence."""

    actions: list[Action] = field(default_factory=list)
    """Ordered list of actions in this sequence."""

    skip_decision: bool = False
    """True when submitted by external modules (prediction layer etc.).
    These actions have lower priority than user-triggered decision actions.
    v4.5.0 §7.2.1 ¶4"""

    source: str = "decision"
    """Origin of this sequence: 'decision', 'prediction', 'reflex', etc."""

    def get_ready_actions(
        self, elapsed_ms: int, tolerance_ms: int = DEFAULT_DISPATCH_TOLERANCE_MS
    ) -> list[Action]:
        """Return actions whose start_ms <= elapsed_ms + tolerance_ms.

        v4.5.0 §7.2.2: On each audio chunk with elapsed_ms, pull all actions
        where start_ms <= elapsed_ms + 50ms and execute them.
        """
        threshold = elapsed_ms + tolerance_ms
        return [a for a in self.actions if a.start_ms <= threshold]

    def get_channel_actions(self, channel: str) -> list[Action]:
        """Filter actions by target channel."""
        return [a for a in self.actions if a.channel == channel]

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict matching the spec JSON format."""
        return {
            "sequence_id": self.sequence_id,
            "actions": [
                {
                    "channel": a.channel,
                    "type": a.type,
                    **({"value": a.value} if a.value is not None else {}),
                    **({"target": a.target} if a.target is not None else {}),
                    "start_ms": a.start_ms,
                    **(
                        {"duration_ms": a.duration_ms}
                        if a.duration_ms is not None
                        else {}
                    ),
                    **(
                        {"deadline_ms": a.deadline_ms}
                        if a.deadline_ms is not None
                        else {}
                    ),
                }
                for a in self.actions
            ],
        }

    def __bool__(self) -> bool:
        """An empty sequence is falsy."""
        return bool(self.actions)


# ---------------------------------------------------------------------------
# CharDurationPredictor — re-exported from tts_service (v4.5.0 §7.2.1 ¶1)
# ---------------------------------------------------------------------------
# Kept here for backward compatibility — the canonical definition is in
# src.execution.tts_service.char_duration_predictor.

# ---------------------------------------------------------------------------
# ActionSequenceScheduler — v4.5.0 §7.2
# ---------------------------------------------------------------------------


class ActionSequenceScheduler:
    """Unified timeline action scheduler.

    v4.5.0 §7.2: Generates ActionSequence scripts, distributes them to
    execution channels, tracks TTS progress, and handles interrupts.

    The scheduler owns the unified timeline: TTS streaming progress
    (elapsed_ms) is the single clock source driving dispatch to all
    three channels (avatar, mouse, voice/bubble). Channels consume
    independently and report status via StateBus (Redis Stream state:global).
    """

    def __init__(self, config: RuntimeConfig, state_bus: StateBus | None = None) -> None:
        """Initialise the scheduler.

        Args:
            config: RuntimeConfig singleton — v4.5.0 §0.5.
            state_bus: Optional StateBus for progress reporting — v4.5.0 §7.6.
        """
        self._config: RuntimeConfig = config
        self._char_predictor: CharDurationPredictor = CharDurationPredictor()
        self._state_bus: StateBus | None = state_bus

        # Active sequence — user-triggered takes priority
        self._active_sequence: ActionSequence | None = None

        # External sequences (skip_decision=True) — lower priority
        self._external_sequences: list[ActionSequence] = []

        # Track dispatched action indices per channel for progress reporting
        self._dispatched_indices: dict[str, int] = {}

        # Interrupt state
        self._interrupted: bool = False

        # Unified timeline clock — the single clock source for all channels
        self._current_elapsed_ms: int = 0

        # Progress callbacks — notified on each TTS progress update
        self._progress_callbacks: list[Callable[[int], None]] = []

        # Track dispatched action identity tuples to avoid re-dispatch
        # (channel, type, value, start_ms) tuples
        self._dispatched_actions: set[tuple[str, str, str | None, int]] = set()

    # ------------------------------------------------------------------
    # Sequence creation — v4.5.0 §7.2.1
    # ------------------------------------------------------------------

    def create_sequence(
        self,
        actions: list[Action],
        text: str | None = None,
        skip_decision: bool = False,
        source: str = "decision",
    ) -> ActionSequence:
        """Create an ActionSequence from a list of actions.

        If text is provided, CharDurationPredictor estimates word-level
        timing to adjust action start_ms values. When CosyVoice provides
        word-level alignment, that data supersedes the predictor.
        """
        _ = text  # Reserved for CosyVoice word-alignment integration (Task 29)
        sequence = ActionSequence(
            actions=actions,
            skip_decision=skip_decision,
            source=source,
        )
        return sequence

    def create_sequence_from_dict(
        self,
        actions_data: list[dict[str, Any]],  # pyright: ignore[reportExplicitAny]
        text: str | None = None,
        skip_decision: bool = False,
        source: str = "decision",
    ) -> ActionSequence:
        """Create an ActionSequence from raw dict data (spec JSON format).

        Args:
            actions_data: List of action dicts matching spec format.
            text: Optional utterance text for timing estimation.
            skip_decision: True when submitted by external modules.
            source: Origin of the sequence.

        Returns:
            A new ActionSequence.
        """
        actions = [
            Action(
                channel=a["channel"],
                type=a["type"],
                start_ms=a["start_ms"],
                value=a.get("value"),
                target=a.get("target"),
                duration_ms=a.get("duration_ms"),
                deadline_ms=a.get("deadline_ms"),
            )
            for a in actions_data
        ]
        return self.create_sequence(actions, text, skip_decision, source)

    # ------------------------------------------------------------------
    # TTS progress-driven dispatch — v4.5.0 §7.2.2
    # ------------------------------------------------------------------

    def get_ready_actions(
        self,
        elapsed_ms: int,
        tolerance_ms: int = DEFAULT_DISPATCH_TOLERANCE_MS,
    ) -> list[Action]:
        """Return actions from the active sequence ready for dispatch.

        v4.5.0 §7.2.2: On each CosyVoice audio chunk carrying elapsed_ms,
        pull all actions where start_ms <= elapsed_ms + 50ms.

        User-triggered sequences have priority over skip_decision sequences.
        If a user interrupt has been signalled, returns empty list.

        Args:
            elapsed_ms: Current TTS stream progress in milliseconds.
            tolerance_ms: Dispatch tolerance window in ms.

        Returns:
            List of Action objects ready for immediate execution.
        """
        if self._interrupted:
            return []

        # User-triggered sequence takes priority
        if self._active_sequence and not self._active_sequence.skip_decision:
            return self._active_sequence.get_ready_actions(elapsed_ms, tolerance_ms)

        # Fall back to external sequences
        for seq in self._external_sequences:
            ready = seq.get_ready_actions(elapsed_ms, tolerance_ms)
            if ready:
                return ready

        # Check active sequence even if it's skip_decision
        if self._active_sequence:
            return self._active_sequence.get_ready_actions(elapsed_ms, tolerance_ms)

        return []

    def get_channel_actions(
        self, channel: str, elapsed_ms: int, tolerance_ms: int = DEFAULT_DISPATCH_TOLERANCE_MS
    ) -> list[Action]:
        """Return ready actions filtered by channel.

        Args:
            channel: Target channel name.
            elapsed_ms: Current TTS progress.
            tolerance_ms: Dispatch tolerance in ms.

        Returns:
            Actions for the specified channel ready for dispatch.
        """
        ready = self.get_ready_actions(elapsed_ms, tolerance_ms)
        return [a for a in ready if a.channel == channel]

    # ------------------------------------------------------------------
    # External submission — v4.5.0 §7.2.1 ¶4
    # ------------------------------------------------------------------

    def submit_external(
        self,
        actions: list[Action],
        source: str = "prediction",
    ) -> ActionSequence:
        """Accept an ActionSequence from an external module.

        v4.5.0 §7.2.1 ¶4: skip_decision=True allows external modules
        (prediction layer) to submit action sequences directly. These
        have lower priority than user-triggered decision actions.

        Args:
            actions: List of Action objects.
            source: Origin module name (e.g., 'prediction').

        Returns:
            The created ActionSequence (with skip_decision=True).
        """
        sequence = self.create_sequence(
            actions=actions,
            skip_decision=True,
            source=source,
        )
        self._external_sequences.append(sequence)
        logger.info(
            "External sequence %s accepted from %s — skip_decision=True, lower priority. trace_id=TBD",
            sequence.sequence_id,
            source,
        )
        return sequence

    def submit_external_from_dict(
        self,
        actions_data: list[dict[str, Any]],  # pyright: ignore[reportExplicitAny]
        source: str = "prediction",
    ) -> ActionSequence:
        """Accept external ActionSequence from raw dict data.

        Args:
            actions_data: List of action dicts.
            source: Origin module name.

        Returns:
            The created ActionSequence.
        """
        actions = [
            Action(
                channel=a["channel"],
                type=a["type"],
                start_ms=a["start_ms"],
                value=a.get("value"),
                target=a.get("target"),
                duration_ms=a.get("duration_ms"),
                deadline_ms=a.get("deadline_ms"),
            )
            for a in actions_data
        ]
        return self.submit_external(actions, source)

    # ------------------------------------------------------------------
    # Active sequence management
    # ------------------------------------------------------------------

    def set_active_sequence(self, sequence: ActionSequence) -> None:
        """Set the primary (user-triggered) active sequence.

        This replaces any existing active sequence. External sequences
        are preserved but have lower priority.
        """
        self._active_sequence = sequence
        self._interrupted = False
        self._dispatched_indices = {}
        logger.info(
            "Active sequence %s set (skip_decision=%s, source=%s). trace_id=TBD",
            sequence.sequence_id,
            sequence.skip_decision,
            sequence.source,
        )

    def clear_active_sequence(self) -> None:
        """Clear the active sequence (e.g., after completion)."""
        self._active_sequence = None
        self._dispatched_indices = {}

    def clear_external_sequences(self) -> None:
        """Clear all external (skip_decision) sequences."""
        self._external_sequences.clear()

    # ------------------------------------------------------------------
    # Interrupt handling — v4.5.0 §7.2.2 ¶2
    # ------------------------------------------------------------------

    def interrupt(self) -> None:
        """Signal user mid-speech interrupt.

        v4.5.0 §7.2.2 ¶2: On user interrupt, immediately stop all channels.
        Channels should play regression animation and return mouse to rest
        position. External sequences are also cleared.
        """
        self._interrupted = True
        self._external_sequences.clear()
        logger.info(
            "User interrupt signalled — all channels stopped, mouse returning to rest. trace_id=TBD"
        )

    def reset_interrupt(self) -> None:
        """Reset interrupt flag for a new sequence."""
        self._interrupted = False

    @property
    def is_interrupted(self) -> bool:
        """Whether an interrupt has been signalled."""
        return self._interrupted

    # ------------------------------------------------------------------
    # CharDurationPredictor access — v4.5.0 §7.2.1 ¶1
    # ------------------------------------------------------------------

    def estimate_timing(self, text: str) -> list[dict[str, Any]]:
        """Estimate per-word/char timing using CharDurationPredictor.

        This is the fallback path when CosyVoice does not provide word-level
        alignment. The predictor provides approximate ms offsets that the
        scheduler uses to position actions on the timeline.

        Args:
            text: The utterance text to estimate timing for.

        Returns:
            List of {"word": str, "start_ms": int, "end_ms": int} dicts.
        """
        return self._char_predictor.predict_durations(text)

    def estimate_total_duration_ms(self, text: str) -> int:
        """Return estimated total speech duration for text in ms."""
        return self._char_predictor.total_duration_ms(text)

    # ------------------------------------------------------------------
    # Mouse deadline enforcement — v4.5.0 §7.2.2 ¶1
    # ------------------------------------------------------------------

    def check_mouse_deadlines(
        self,
        elapsed_ms: int,
        threshold_ms: int = DEFAULT_MOUSE_DEADLINE_THRESHOLD_MS,
    ) -> list[Action]:
        """Find mouse actions approaching or past their deadline.

        v4.5.0 §7.2.2: If mouse is near deadline and not yet at target,
        force-jump to target coordinates.

        Args:
            elapsed_ms: Current TTS progress.
            threshold_ms: If remaining time < this, action is urgent.

        Returns:
            List of urgent mouse actions that should force-jump.
        """
        urgent: list[Action] = []
        if self._active_sequence is None:
            return urgent

        for a in self._active_sequence.actions:
            if a.channel != CHANNEL_MOUSE or a.deadline_ms is None:
                continue
            remaining = a.deadline_ms - elapsed_ms
            if remaining <= threshold_ms:
                urgent.append(a)

        return urgent

    # ------------------------------------------------------------------
    # Channel dispatch — v4.5.0 §7.2.3
    # ------------------------------------------------------------------

    def dispatch_to_channels(
        self, elapsed_ms: int, tolerance_ms: int = DEFAULT_DISPATCH_TOLERANCE_MS
    ) -> dict[str, list[Action]]:
        """Distribute ready actions to their respective channels.

        v4.5.0 §7.2.3: Each channel runs as an independent coroutine,
        consuming its own actions from the sequence. The scheduler
        groups actions by channel for efficient distribution.

        Args:
            elapsed_ms: Current TTS progress.
            tolerance_ms: Dispatch tolerance.

        Returns:
            Dict mapping channel name to list of ready Action objects.
        """
        ready = self.get_ready_actions(elapsed_ms, tolerance_ms)
        dispatch: dict[str, list[Action]] = {
            CHANNEL_AVATAR: [],
            CHANNEL_MOUSE: [],
            CHANNEL_VOICE: [],
            CHANNEL_BUBBLE: [],
        }
        for a in ready:
            if a.channel in dispatch:
                dispatch[a.channel].append(a)
        return dispatch


# ---------------------------------------------------------------------------
# ActionScheduler — priority-gated action dispatcher for runtime_loop
# v4.5.0 §7.2 (supplemental)
#
# Lighter than ActionSequenceScheduler (no timeline/timing).  Provides
# a priority queue so voice actions always preempt mouse actions.
# Intended for use in run_voice_loop() — NOT inside DecisionBridge.
# ---------------------------------------------------------------------------


class ActionScheduler:
    """Priority-based action dispatcher for voice and mouse actions.

    v4.5.0 §7.2 — Voice playback (priority=0) always takes precedence
    over mouse actions (priority=1).  When TTS is in-flight mouse actions
    are deferred; a user interrupt (SIGINT / reflex stop_tts) clears the
    queue via :meth:`clear_queue`.

    Lifecycle:
        _scheduler = ActionScheduler()
        _scheduler.register_action("voice", lambda text: tts.speak(text), priority=0)
        _scheduler.register_action("mouse_click", lambda x, y: mouse.click(x, y), priority=1)
        await _scheduler.enqueue("voice", text=reply)
        _scheduler.clear_queue()   # on interrupt
    """

    def __init__(self) -> None:
        self._actions: dict[str, tuple[Callable[..., Awaitable[object]], int]] = {}
        """name → (async-callback, priority)  (lower = higher urgency)"""

        self._voice_active: bool = False
        """True while a voice action is executing (blocks mouse)."""

        self._cancelled: bool = False
        """Set by clear_queue(); checked by pending waiters to bail out."""

    # ------------------------------------------------------------------
    # Registration
    # ------------------------------------------------------------------

    def register_action(
        self,
        name: str,
        callback: Callable[..., Awaitable[object]],
        priority: int = 0,
    ) -> None:
        """Register an async callback for an action name.

        Args:
            name: Action identifier (e.g. ``"voice"``, ``"mouse_click"``).
            callback: Awaitable that receives kwargs from :meth:`enqueue`.
            priority: Lower number = higher urgency.  0 = voice, 1 = mouse.
        """
        self._actions[name] = (callback, priority)

    # ------------------------------------------------------------------
    # Execution
    # ------------------------------------------------------------------

    async def enqueue(self, name: str, **kwargs: object) -> object:
        """Execute the named action, respecting priority ordering.

        * Voice actions set ``_voice_active`` for their duration.
        * Non-voice actions spin-wait while ``_voice_active`` is True,
          and bail out immediately when ``_cancelled`` is set.
        * Returns the callback's return value (e.g. ``bool`` for mouse clicks).
        """
        if name not in self._actions:
            logger.warning(
                "Unknown action %r — ignored. Registered: %s",
                name,
                sorted(self._actions.keys()),
            )
            return None

        callback, _priority = self._actions[name]

        if name == "voice":
            self._voice_active = True
            try:
                return await callback(**kwargs)  # type: ignore[arg-type]
            finally:
                self._voice_active = False
        else:
            # Mouse / other low-priority actions: wait until voice finishes
            # or clear_queue cancels them.
            while self._voice_active and not self._cancelled:
                await asyncio.sleep(0.05)
            if not self._cancelled:
                return await callback(**kwargs)  # type: ignore[arg-type]
            return False

    # ------------------------------------------------------------------
    # Interrupt / lifecycle
    # ------------------------------------------------------------------

    def clear_queue(self) -> None:
        """Cancel all pending actions (user interrupt / reflex stop_tts).

        Sets ``_cancelled`` which causes pending mouse waiters to bail.
        Does NOT kill the in-flight voice async task — the TTS pipeline
        handles that via its own stop mechanism.
        """
        self._cancelled = True
        logger.info("ActionScheduler queue cleared (interrupt).")

    def reset(self) -> None:
        """Reset cancelled flag for the next interaction cycle."""
        self._cancelled = False
        self._voice_active = False
